# Data Cleaning

This notebook is primarily to explore and clean the datasets we are working on.

## Citibike Data

In [2]:
import pandas as pd

citibike_db = pd.read_csv('Datasets\Citibike\\202501-citibike-tripdata_1.csv')
citibike_db.head()

<>:3: SyntaxWarning: invalid escape sequence '\C'
<>:3: SyntaxWarning: invalid escape sequence '\C'
C:\Users\larry\AppData\Local\Temp\ipykernel_34812\3844117713.py:3: SyntaxWarning: invalid escape sequence '\C'
  citibike_db = pd.read_csv('Datasets\Citibike\\202501-citibike-tripdata_1.csv')
C:\Users\larry\AppData\Local\Temp\ipykernel_34812\3844117713.py:3: DtypeWarning: Columns (0: start_station_id, 1: end_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  citibike_db = pd.read_csv('Datasets\Citibike\\202501-citibike-tripdata_1.csv')

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,ACCC919B5A3CD9AD,electric_bike,2025-01-01 14:52:26.542,2025-01-01 14:59:53.427,W 20 St & 7 Ave,6182.02,E 10 St & 2 Ave,5746.02,40.742388,-73.997262,40.729708,-73.986598,casual
1,1FABDF3EE40FCB0E,classic_bike,2025-01-10 05:03:13.646,2025-01-10 05:13:13.331,W 20 St & 7 Ave,6182.02,E 25 St & 1 Ave,6004.07,40.742388,-73.997262,40.738177,-73.977387,member
2,88F0F3CFCBC79652,classic_bike,2025-01-13 13:40:17.630,2025-01-13 13:47:05.817,St James Pl & Oliver St,5238.05,Fulton St & William St,5137.11,40.713079,-73.998512,40.709601,-74.006551,member
3,6FDE4E191D58E453,electric_bike,2025-01-10 08:29:16.996,2025-01-10 08:34:49.360,St James Pl & Oliver St,5238.05,Fulton St & William St,5137.11,40.713079,-73.998512,40.709601,-74.006551,member
4,E9B03B9F77A85455,electric_bike,2025-01-11 18:59:48.427,2025-01-11 19:13:21.292,E 33 St & 1 Ave,6197.08,Allen St & Rivington St,5414.06,40.743227,-73.974498,40.720196,-73.989978,member

In [3]:
citibike_db.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 13 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   ride_id             1000000 non-null  str
 1   rideable_type       1000000 non-null  str
 2   started_at          1000000 non-null  str
 3   ended_at            1000000 non-null  str
 4   start_station_name  999685 non-null   str
 5   start_station_id    999685 non-null   object
 6   end_station_name    998051 non-null   str
 7   end_station_id      997848 non-null   object
 8   start_lat           999685 non-null   float64
 9   start_lng           999685 non-null   float64
 10  end_lat             997853 non-null   float64
 11  end_lng             997853 non-null   float64
 12  member_casual       1000000 non-null  str
dtypes: float64(4), object(2), str(7)
memory usage: 99.2+ MB

In [4]:
citibike_db = citibike_db.drop(columns=['start_station_id', 'end_station_id', 'ride_id', 'member_casual'])
citibike_db.head()

,rideable_type,started_at,ended_at,start_station_name,end_station_name,start_lat,start_lng,end_lat,end_lng
0,electric_bike,2025-01-01 14:52:26.542,2025-01-01 14:59:53.427,W 20 St & 7 Ave,E 10 St & 2 Ave,40.742388,-73.997262,40.729708,-73.986598
1,classic_bike,2025-01-10 05:03:13.646,2025-01-10 05:13:13.331,W 20 St & 7 Ave,E 25 St & 1 Ave,40.742388,-73.997262,40.738177,-73.977387
2,classic_bike,2025-01-13 13:40:17.630,2025-01-13 13:47:05.817,St James Pl & Oliver St,Fulton St & William St,40.713079,-73.998512,40.709601,-74.006551
3,electric_bike,2025-01-10 08:29:16.996,2025-01-10 08:34:49.360,St James Pl & Oliver St,Fulton St & William St,40.713079,-73.998512,40.709601,-74.006551
4,electric_bike,2025-01-11 18:59:48.427,2025-01-11 19:13:21.292,E 33 St & 1 Ave,Allen St & Rivington St,40.743227,-73.974498,40.720196,-73.989978

In [5]:
citibike_db.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 9 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   rideable_type       1000000 non-null  str
 1   started_at          1000000 non-null  str
 2   ended_at            1000000 non-null  str
 3   start_station_name  999685 non-null   str
 4   end_station_name    998051 non-null   str
 5   start_lat           999685 non-null   float64
 6   start_lng           999685 non-null   float64
 7   end_lat             997853 non-null   float64
 8   end_lng             997853 non-null   float64
dtypes: float64(4), str(5)
memory usage: 68.7 MB

In [7]:
citibike_db = citibike_db[citibike_db['end_lat'].notna()]
citibike_db.info()

<class 'pandas.DataFrame'>
Index: 997853 entries, 0 to 999999
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   rideable_type       997853 non-null  str
 1   started_at          997853 non-null  str
 2   ended_at            997853 non-null  str
 3   start_station_name  997586 non-null  str
 4   end_station_name    997848 non-null  str
 5   start_lat           997586 non-null  float64
 6   start_lng           997586 non-null  float64
 7   end_lat             997853 non-null  float64
 8   end_lng             997853 non-null  float64
dtypes: float64(4), str(5)
memory usage: 76.1 MB

In [13]:
citibike_db[citibike_db['end_station_name'].isna()].head()

,rideable_type,started_at,ended_at,start_station_name,end_station_name,start_lat,start_lng,end_lat,end_lng
2118,electric_bike,2025-01-29 13:34:31.082,2025-01-29 14:36:52.637,York St & Marin Blvd,NaN,40.716615,-74.042412,40.72,-74.04
2318,electric_bike,2025-01-17 08:12:54.168,2025-01-17 08:18:29.246,6 St & Grand St,NaN,40.744398,-74.034501,40.74,-74.03
2319,electric_bike,2025-01-09 11:54:06.770,2025-01-09 12:58:13.472,York St & Marin Blvd,NaN,40.716615,-74.042412,40.72,-74.04
2320,electric_bike,2025-01-09 06:39:58.283,2025-01-09 07:34:28.310,Union St,NaN,40.718211,-74.083639,40.72,-74.04
2321,electric_bike,2025-01-05 17:32:39.443,2025-01-05 18:17:42.193,8 St & Washington St,NaN,40.745984,-74.028199,40.71,-74.06