# Data Cleaning

This notebook is primarily to explore and clean the datasets we are working on.

## Citibike Data

In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\georg\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\georg\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\georg\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\georg\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\georg\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\georg\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

citibike_db = pd.read_csv('Datasets\Citibike\JC-202501-citibike-tripdata.csv')
citibike_db.head()

<>:3: SyntaxWarning: invalid escape sequence '\C'
<>:3: SyntaxWarning: invalid escape sequence '\C'
C:\Users\georg\AppData\Local\Temp\ipykernel_39260\1225199878.py:3: SyntaxWarning: invalid escape sequence '\C'
  citibike_db = pd.read_csv('Datasets\Citibike\JC-202501-citibike-tripdata.csv')

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,40.742677,-74.051789,member
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,40.711130,-74.078900,member
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member

In [10]:
citibike_db = citibike_db.drop(columns=['start_station_id', 'end_station_id', 'ride_id', 'member_casual'])
citibike_db.head()

,rideable_type,started_at,ended_at,start_station_name,end_station_name,start_lat,start_lng,end_lat,end_lng
0,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,Pershing Field,40.731169,-74.057574,40.742677,-74.051789
1,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,Jackson Square,40.731169,-74.057574,40.711130,-74.078900
2,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,Hoboken Terminal - Hudson St & Hudson Pl,40.731169,-74.057574,40.735938,-74.030305
3,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,Hoboken Terminal - Hudson St & Hudson Pl,40.731169,-74.057574,40.735938,-74.030305
4,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,Hoboken Terminal - Hudson St & Hudson Pl,40.731169,-74.057574,40.735938,-74.030305

In [11]:
citibike_db.info()

<class 'pandas.DataFrame'>
RangeIndex: 50611 entries, 0 to 50610
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rideable_type       50611 non-null  str
 1   started_at          50611 non-null  str
 2   ended_at            50611 non-null  str
 3   start_station_name  50611 non-null  str
 4   end_station_name    50504 non-null  str
 5   start_lat           50611 non-null  float64
 6   start_lng           50611 non-null  float64
 7   end_lat             50592 non-null  float64
 8   end_lng             50592 non-null  float64
dtypes: float64(4), str(5)
memory usage: 3.5 MB

In [12]:
citibike_db = citibike_db[citibike_db['end_lat'].notna()]
citibike_db.info()

<class 'pandas.DataFrame'>
Index: 50592 entries, 0 to 50610
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rideable_type       50592 non-null  str
 1   started_at          50592 non-null  str
 2   ended_at            50592 non-null  str
 3   start_station_name  50592 non-null  str
 4   end_station_name    50504 non-null  str
 5   start_lat           50592 non-null  float64
 6   start_lng           50592 non-null  float64
 7   end_lat             50592 non-null  float64
 8   end_lng             50592 non-null  float64
dtypes: float64(4), str(5)
memory usage: 3.9 MB

In [15]:
citibike_db[citibike_db['end_lng'] == "-74.04"]

Empty DataFrame
Columns: [rideable_type, started_at, ended_at, start_station_name, end_station_name, start_lat, start_lng, end_lat, end_lng]
Index: []

In [13]:
citibike_db[citibike_db['end_station_name'].isna()].head()

,rideable_type,started_at,ended_at,start_station_name,end_station_name,start_lat,start_lng,end_lat,end_lng
2118,electric_bike,2025-01-29 13:34:31.082,2025-01-29 14:36:52.637,York St & Marin Blvd,NaN,40.716615,-74.042412,40.72,-74.04
2318,electric_bike,2025-01-17 08:12:54.168,2025-01-17 08:18:29.246,6 St & Grand St,NaN,40.744398,-74.034501,40.74,-74.03
2319,electric_bike,2025-01-09 11:54:06.770,2025-01-09 12:58:13.472,York St & Marin Blvd,NaN,40.716615,-74.042412,40.72,-74.04
2320,electric_bike,2025-01-09 06:39:58.283,2025-01-09 07:34:28.310,Union St,NaN,40.718211,-74.083639,40.72,-74.04
2321,electric_bike,2025-01-05 17:32:39.443,2025-01-05 18:17:42.193,8 St & Washington St,NaN,40.745984,-74.028199,40.71,-74.06